---
driver:
  name: vagrant

provisioner:
  name: dummy

platforms:
  - name: qwerty1979/nginx64

verifier:
  name: inspec

suites:
  - name: default
    verifier:
      inspec_tests:
        - nginx_test.rb
